#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
XML Cleaning Script for ACME with Configuration Support

Cleans generated XML output from kramdown-rfc2629, with settings
loaded automatically from config files.
"""

import re
import sys
import os

# Add parent directory to path to import config_loader
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config_loader import ConfigLoader, ConfigLoadError


class XMLCleaner:
    """Cleans RFC XML output according to IETF standards."""
    
    def __init__(self, config=None):
        """
        Initialize the XML cleaner.
        
        Args:
            config: Configuration dictionary with cleaning options.
                   If None, loads from config files automatically.
        """
        if config is None:
            try:
                loader = ConfigLoader()
                config = loader.load(required=False)
            except ConfigLoadError as e:
                print(f"[WARNING] {e}", file=sys.stderr)
                config = {}
        
        self.config = config
        self.md_skip = False
        self.rfced_remove = False
    
    def clean_line(self, line):
        """
        Clean a single line of XML.
        
        Args:
            line: The line to clean.
            
        Returns:
            The cleaned line (or None if line should be skipped).
        """
        # Strip newline
        line = line.rstrip()
        
        # Strip the kramdown-rfc2629 attribution line
        if re.search(r'<!-- generated by', line):
            return None
        
        # Remove unnecessary whitespace in tags
        line = re.sub(r' +/>', '/>', line)
        line = re.sub(r' +>', '>', line)
        
        # Fix smart quotes
        line = re.sub(r'"', '"', line)
        line = re.sub(r'"', '"', line)
        line = re.sub(r''', "'", line)
        line = re.sub(r''', "'", line)
        
        # Fix smart dashes
        line = re.sub(r'–', "--", line)
        
        # Fix smart ellipses
        line = re.sub(r'…', "...", line)
        
        # Strip Markdown-source
        if not self.md_skip:
            self.md_skip = re.match(r'<!-- ##markdown-source:', line)
        if self.md_skip:
            self.md_skip = not re.match(r'-->', line)
            return None
        
        # Strip the kramdown-rfc2629 credit
        if re.match(r'<!-- generated by ', line):
            return None
        
        return line
    
    def clean(self, input_file=None, output_file=None):
        """
        Clean XML input.
        
        Args:
            input_file: Input file handle. Defaults to stdin.
            output_file: Output file handle. Defaults to stdout.
        """
        if input_file is None:
            input_file = sys.stdin
        if output_file is None:
            output_file = sys.stdout
        
        for line in input_file:
            cleaned = self.clean_line(line)
            if cleaned is not None:
                output_file.write(cleaned + '\n')


def main():
    """Main entry point."""
    try:
        cleaner = XMLCleaner()
        cleaner.clean()
    except ConfigLoadError as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        sys.exit(1)
    except KeyboardInterrupt:
        sys.exit(1)
    except Exception as e:
        print(f"[ERROR] Unexpected error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
